# Generated by Django 4.0.5 on 2022-06-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrux', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm_items',
            name='datetime',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='farm_items',
            name='f_items',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='farm_items',
            name='f_quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='farm_items',
            name='f_total',
            field=models.IntegerField(default=None),
        ),
    ]
